name: Build and Deploy to App Services (Microsoft Azure)
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                    node-version: '18.x'
            

            - name: Dependencies installation
              run: 
                npm install 
            
            # - name: Artifact for deployment
            #   run: zip realease.zip ./* -r
            
            # - name: Upload artifact
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: node-app
            #     path: release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: 'Run Azure webapp deploy action using publish profile credentials'
              uses: azure/webapps-deploy@v2
              with:
                app-name: htmlex3
                publish-profile: ${{ secrets.azureWebAppPublishProfile }}


